# Generated by Django 3.1.1 on 2020-09-06 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pet_type', models.CharField(choices=[('', 'Tipo de mascota'), ('Gato', 'Gato'), ('Perro', 'Perro'), ('Pez', 'Pez'), ('Otro', 'Otro')], max_length=10)),
                ('size', models.CharField(choices=[('Pequeno', 'Pequeño'), ('Medio', 'Medio'), ('Grande', 'Grande')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
