# Generated by Django 3.1.1 on 2020-09-06 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('1', 'Cita medica'), ('2', 'Cita Vacunación'), ('3', 'Cita de desparasitación'), ('4', 'Cita de baño'), ('5', 'Cita de corte de pelo')], max_length=10)),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='fecha')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_medical_service', to='pets.pet')),
            ],
        ),
    ]
